import './globals.css';
import FontsProvider from './FontsProvider';
import { AuthProvider } from "./components/context/authcontext";

export const metadata = {
  title: "Frizerski salon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <FontsProvider />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}